// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Required by `prisma migrate diff --from-migrations` in Prisma 7.
    // Falls back to the main DB locally; CI overrides with a dedicated shadow URL.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
